<?php
namespace OSE\TimeClockBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntryRepository extends EntityRepository
{
    public function findAllEntriesByUserId($user_id)
    {

        $entries = $this->getEntityManager()
            ->createQuery(
                'SELECT e FROM OSE\TimeClockBundle\Entity\Entry e 
                 WHERE e.user_id = :userid ORDER BY e.time ASC')
            ->setParameter('userid',$user_id)
            ->getResult();

        return $entries;
    }
} 
