OSE\UserBundle\Entity\User:
    type: entity
    table: fos_user
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    oneToMany:
        entries:
            targetEntity: OSE\TimeClockBundle\Entity\Entry
            mappedBy: User
    lifecycleCallbacks: {  }
