parameters:
#    ose_time_clock.example.class: OSE\TimeClockBundle\Example

services:
    ose_time_clock.entrycalc:
        class: OSE\TimeClockBundle\Utility\EntryCalculatorUtility
        arguments: ['@doctrine.orm.entity_manager']
