parameters:
#    ose_time_clock.example.class: OSE\TimeClockBundle\Example

services:
#    ose_time_clock.example:
#        class: %ose_time_clock.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
