OSE\TimeClockBundle\Entity\Entry:
    type: entity
    repositoryClass: OSE\TimeClockBundle\Entity\Repository\EntryRepository
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        user_id:
            type: integer
            column: user_id
        time:
            type: datetime
        details:
            type: string
            length: 255
            nullable: true
    manyToOne:
        user:
            targetEntity: OSE\UserBundle\Entity\User
            inversedBy: Entry
        entry_type:
            targetEntity: EntryType
            inversedBy: Entry
    lifecycleCallbacks: {  }
